package tandem.model;

// default package
// Generated 2/dez/2015 23:18:39 by Hibernate Tools 4.3.1.Final

/**
 * Authorities generated by hbm2java
 */
public class Authorities implements java.io.Serializable {

	private AuthoritiesId id;
	private Users users;

	public Authorities() {
	}

	public Authorities(AuthoritiesId id, Users users) {
		this.id = id;
		this.users = users;
	}

	public AuthoritiesId getId() {
		return this.id;
	}

	public void setId(AuthoritiesId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
