package tandem.model;

// default package
// Generated 13/dez/2015 21:58:50 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name = "authorities", catalog = "tandem", uniqueConstraints = @UniqueConstraint(columnNames = { "user_fk",
		"authority" }) )
public class Authorities implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private AuthoritiesId id;
	private Users users;

	public Authorities() {
	}

	public Authorities(AuthoritiesId id /*,Users users*/ ) {
		this.id = id;
		//this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userFk", column = @Column(name = "user_fk", nullable = false) ),
			@AttributeOverride(name = "authority", column = @Column(name = "authority", nullable = false, length = 10) ) })
	public AuthoritiesId getId() {
		return this.id;
	}

	public void setId(AuthoritiesId id) {
		this.id = id;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "user_fk", nullable = false, insertable = false, updatable = false)
	@ManyToOne
	@JoinColumn(name="user_fk")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = null; //users;
	}

}
