package tandem.model;

// default package
// Generated 13/dez/2015 21:58:50 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OauthProvider generated by hbm2java
 */
@Entity
@Table(name = "oauth_provider", catalog = "tandem")
public class OauthProvider implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private OauthProviderId id;
	private Users users;
	private Date createdAt;

	public OauthProvider() {
	}

	public OauthProvider(OauthProviderId id /* , Users users*/) {
		this.id = id;
		//this.users = users;
	}

	public OauthProvider(OauthProviderId id,/*Users users,*/ Date createdAt) {
		this.id = id;
		//this.users = users;
		this.createdAt = createdAt;
	}

	@EmbeddedId

	@AttributeOverrides({
		@AttributeOverride(name = "oauthUid", column = @Column(name = "oauth_uid", nullable = false) ),
		@AttributeOverride(name = "oauthProvider", column = @Column(name = "oauth_provider", nullable = false, length = 10) ) })
	public OauthProviderId getId() {
		return this.id;
	}

	public void setId(OauthProviderId id) {
		this.id = id;
	}

	//@ManyToOne
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_fk")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = null; //users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
