package tandem.model;

// default package
// Generated 2/dez/2015 23:18:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private Integer profileId;
	private Users users;
	private byte privacy;
	private Byte rating;
	private String nameNepali;
	private Date dob;
	private String aboutMe;
	private String relationship;
	private String lookingFor;
	private String phone;
	private String interests;
	private String education;
	private String hobbies;
	private String facebookProfile;
	private String googleProfile;
	private String twitterProfile;
	private String locationGps;
	private Byte mainLangFk;
	private String everythingElse;
	private Date createdAt;

	public Profile() {
	}

	public Profile(Users users, byte privacy) {
		this.users = users;
		this.privacy = privacy;
	}

	public Profile(Users users, byte privacy, Byte rating, String nameNepali, Date dob, String aboutMe,
			String relationship, String lookingFor, String phone, String interests, String education, String hobbies,
			String facebookProfile, String googleProfile, String twitterProfile, String locationGps, Byte mainLangFk,
			String everythingElse, Date createdAt) {
		this.users = users;
		this.privacy = privacy;
		this.rating = rating;
		this.nameNepali = nameNepali;
		this.dob = dob;
		this.aboutMe = aboutMe;
		this.relationship = relationship;
		this.lookingFor = lookingFor;
		this.phone = phone;
		this.interests = interests;
		this.education = education;
		this.hobbies = hobbies;
		this.facebookProfile = facebookProfile;
		this.googleProfile = googleProfile;
		this.twitterProfile = twitterProfile;
		this.locationGps = locationGps;
		this.mainLangFk = mainLangFk;
		this.everythingElse = everythingElse;
		this.createdAt = createdAt;
	}

	public Integer getProfileId() {
		return this.profileId;
	}

	public void setProfileId(Integer profileId) {
		this.profileId = profileId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public byte getPrivacy() {
		return this.privacy;
	}

	public void setPrivacy(byte privacy) {
		this.privacy = privacy;
	}

	public Byte getRating() {
		return this.rating;
	}

	public void setRating(Byte rating) {
		this.rating = rating;
	}

	public String getNameNepali() {
		return this.nameNepali;
	}

	public void setNameNepali(String nameNepali) {
		this.nameNepali = nameNepali;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getAboutMe() {
		return this.aboutMe;
	}

	public void setAboutMe(String aboutMe) {
		this.aboutMe = aboutMe;
	}

	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	public String getLookingFor() {
		return this.lookingFor;
	}

	public void setLookingFor(String lookingFor) {
		this.lookingFor = lookingFor;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getInterests() {
		return this.interests;
	}

	public void setInterests(String interests) {
		this.interests = interests;
	}

	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getHobbies() {
		return this.hobbies;
	}

	public void setHobbies(String hobbies) {
		this.hobbies = hobbies;
	}

	public String getFacebookProfile() {
		return this.facebookProfile;
	}

	public void setFacebookProfile(String facebookProfile) {
		this.facebookProfile = facebookProfile;
	}

	public String getGoogleProfile() {
		return this.googleProfile;
	}

	public void setGoogleProfile(String googleProfile) {
		this.googleProfile = googleProfile;
	}

	public String getTwitterProfile() {
		return this.twitterProfile;
	}

	public void setTwitterProfile(String twitterProfile) {
		this.twitterProfile = twitterProfile;
	}

	public String getLocationGps() {
		return this.locationGps;
	}

	public void setLocationGps(String locationGps) {
		this.locationGps = locationGps;
	}

	public Byte getMainLangFk() {
		return this.mainLangFk;
	}

	public void setMainLangFk(Byte mainLangFk) {
		this.mainLangFk = mainLangFk;
	}

	public String getEverythingElse() {
		return this.everythingElse;
	}

	public void setEverythingElse(String everythingElse) {
		this.everythingElse = everythingElse;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
