package tandem.model;

// default package
// Generated 2/dez/2015 23:18:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String password;
	private String firstName;
	private String midName;
	private String lastName;
	private String email;
	private int token;
	private boolean active;
	private byte online;
	private Date createdAt;
	private Set<Profile> profiles = new HashSet<Profile>(0);
	private Set<Authorities> authoritieses = new HashSet<Authorities>(0);

	public Users() {
	}

	public Users(String username, String password, String firstName, String lastName, String email, int token,
			boolean active, byte online, Date createdAt) {
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.token = token;
		this.active = active;
		this.online = online;
		this.createdAt = createdAt;
	}

	public Users(String username, String password, String firstName, String midName, String lastName, String email,
			int token, boolean active, byte online, Date createdAt, Set<Profile> profiles,
			Set<Authorities> authoritieses) {
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.midName = midName;
		this.lastName = lastName;
		this.email = email;
		this.token = token;
		this.active = active;
		this.online = online;
		this.createdAt = createdAt;
		this.profiles = profiles;
		this.authoritieses = authoritieses;
	}
	
	public Users(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMidName() {
		return this.midName;
	}

	public void setMidName(String midName) {
		this.midName = midName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getToken() {
		return this.token;
	}

	public void setToken(int token) {
		this.token = token;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public byte getOnline() {
		return this.online;
	}

	public void setOnline(byte online) {
		this.online = online;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Set<Profile> getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set<Profile> profiles) {
		this.profiles = profiles;
	}

	public Set<Authorities> getAuthoritieses() {
		return this.authoritieses;
	}

	public void setAuthoritieses(Set<Authorities> authoritieses) {
		this.authoritieses = authoritieses;
	}

}
